export const teluguMovies = [
    'Aagantakudu',
    'Vadhu Bava Thappu',
    'Suvarna Sundari',
    'Guleba Kavali Katha',
    'Bhookailas',
    'Dakshayagnam',
    'Joo Lakataka',
    'Patnam Vachina Pathivrathalu',
    'Maavichiguru',
    'Keechurallu',
    'Maa Aavida Meedha Ottu Mee Aavida Chala Manchidi',
    'Kanya Sulkam',
    'Mr Gireesam',
    'Kalanthakulu',
    'Pandanti Kapuram',
    'Kadhali Vachina Kanakadurga',
    'Pellaniki Prema Lekha Priyuraliki Subhalekha',
    'Ramachari Veedo Pedha Gudachari',
    'Burripalem Bullodu',
    'Bhaktha Raghunath',
    'Athanu Hardware Aame Software',
    'Vayasu Pilichindi',
    'Aasthi Jaanedu Aasa Baaredu',
    'Vichitra Daampatyam',
    'Apoorva Sahodarulu',
    'Julakataka',
    'Missamma',
    'Mee Sreyobhilkashi',
    'Sreemadvirata potuluri veerabrhmendra swamy charita',
    'Alex',
    'Padamati Sandhya ragam',
    'Pellaniki premalekha priyuraaliki Subhalekha',
    'Micheal madana kama raju',
    'Kulagotralu',
    'Patnam vachina pativratalu',
    'Mr.Gireesam',
    'Sankalpam',
    'Rojulu Marayi',
    'Ilavelpu',
    'Kanyasulkam',
    'BurriPalem bullodu',
    'Keechurallu',
    'Pavitraprema',
    'Gulebagavali katha',
    'Abhimanam',
    'Bhaktha raghunath',
    'Vanaja',
    'Onamalu',
    'Prasthanam',
    'Broker',
    'Aasti janedu Aasa mooredu'
]